#!/usr/bin/env python3
"""Generate ordering-questions.json covering every grammar point in grammar-questions.js."""
import json, os

# Each entry: (lesson, grammar, prefix, [4 tokens], suffix, star_slot_1_indexed, explanation_ja, translation_en)
Q = [
    # ========== Lesson 1 ==========
    (1, "～際に", "", ["海外へ","出張する","際には","現地の"], "法律を事前に調べておくべきだ。", 3,
     "「～とき」の硬い表現で、改まった場面や書き言葉でよく使われる。",
     "When traveling abroad for business, you should look into local laws in advance."),
    (1, "～にあたって", "", ["新入生を","迎えるに","あたり","校長が"], "歓迎の言葉を述べた。", 3,
     "何か重要なことを始める場面で「～する時に」の意味を表す改まった表現。",
     "On the occasion of welcoming the new students, the principal gave a welcoming address."),
    (1, "～とたんに", "", ["ドアを","開けた","とたん","猫が"], "外に飛び出していった。", 2,
     "動作の直後に予想外の出来事が起こることを表す。前後がほぼ同時。",
     "The moment I opened the door, the cat ran outside."),
    (1, "～かと思うと", "", ["娘は","学校から","帰ったかと","思うと"], "すぐ友達の家へ出かけた。", 3,
     "ある動作の直後にすぐ別のことが起こる様子を表す。意外性を伴うことが多い。",
     "No sooner had my daughter come home from school than she went to a friend's house."),
    (1, "～かのうちに", "", ["電車の","ドアが","閉まるか","閉まらないかの"], "うちに走って乗り込んだ。", 3,
     "二つの動作がほぼ同時に起こることを表す。するかしないかのギリギリのタイミング。",
     "The moment the train doors were about to close, I ran in and boarded."),

    # ========== Lesson 2 ==========
    (2, "～最中に", "", ["会議の","最中に","突然","携帯が"], "鳴ってしまい、恥ずかしかった。", 2,
     "まさに進行中の動作の途中で別の出来事が割り込むことを強調する表現。",
     "Right in the middle of the meeting, my phone suddenly rang, and it was embarrassing."),
    (2, "～うちに", "", ["雨が","降らない","うちに","洗濯物を"], "取り込んでおこう。", 3,
     "ある状態が続いている間に行動すべきだという含みを持つ。状態が変わる前にという意味。",
     "Let's bring the laundry in before it starts to rain."),
    (2, "～一方だ", "", ["インターネットの","普及で","情報量は","増える"], "一方だ。", 4,
     "変化が一方向にますます進み続けている様子を表す。止まらない傾向。",
     "With the spread of the internet, the amount of information just keeps increasing."),
    (2, "～ところだ", "", ["ちょうど","晩ご飯を","食べる","ところだった"], "ので、電話に出られなかった。", 3,
     "動作の段階（直前・最中・直後）を表す。「ちょうど今」のタイミングを示す。",
     "I couldn't answer the phone because I was just about to eat dinner."),
    (2, "～つつある", "", ["地球の","温暖化は","急速に","進行しつつある"], "と言われている。", 4,
     "変化が徐々に継続している様子を書き言葉で表す。フォーマルな進行表現。",
     "It is said that global warming is progressing rapidly."),
    (2, "～つつ/ながら", "", ["仕事を","続けつつ","大学院で","勉強する"], "のはとても大変だ。", 2,
     "二つの動作の同時進行を表す、やや硬い表現。",
     "Continuing to work while studying in graduate school is extremely demanding."),
    (2, "～している(進行中)", "", ["今","母は","台所で","料理をしている"], "ところです。", 4,
     "動作の進行中や状態の継続を表す基本表現。",
     "Right now my mother is in the kitchen cooking."),

    # ========== Lesson 3 ==========
    (3, "～はじめて", "", ["親に","なってから","子育ての","大変さを"], "はじめて実感した。", 4,
     "経験を通じて初めて何かに気づくことを表す。それまで知らなかったという含み。",
     "Only after becoming a parent did I truly realize how difficult child-rearing is."),
    (3, "～上で", "", ["契約書を","よく読んだ","上で","サインを"], "してください。", 2,
     "ある動作をしてから、その結果を踏まえて次の行動をすることを示す。順序と根拠の表現。",
     "Please sign only after carefully reading the contract."),
    (3, "～次第", "", ["先方から","連絡が","あり","次第"], "すぐに知らせます。", 4,
     "ある動作が完了したらすぐに次の行動を起こすことを表す。ビジネスでよく使われる。",
     "As soon as we hear back from the other party, I'll let you know immediately."),
    (3, "～以来", "", ["あの","事故","以来","彼は"], "二度と車に乗っていない。", 3,
     "ある出来事を起点として、それからずっと続いている状態を表す。",
     "Ever since that accident, he has not gotten into a car again."),
    (3, "～からでないと", "", ["登録を","済ませて","からでないと","会員サービスは"], "ご利用いただけません。", 3,
     "先にある動作を完了しなければ次のことができないという必要条件を示す。",
     "You cannot use our member services until after you have completed registration."),
    (3, "～後で", "", ["会議が","終わった","後で","資料を"], "送ってください。", 3,
     "時間の前後関係を明確にし、ある動作の後に次の行動をすることを示す基本表現。",
     "Please send the materials after the meeting is over."),

    # ========== Lesson 4 ==========
    (4, "～をはじめ", "", ["日本は","東京を","はじめ","多くの"], "都市で人口が集中している。", 3,
     "多くのものの中から代表的な一つを挙げ、他にもあることを示す例示表現。",
     "In Japan, starting with Tokyo, population is concentrated in many cities."),
    (4, "～からして", "", ["あの","店は","料理の","見た目からして"], "プロの腕前だとわかる。", 4,
     "一つの例や手がかりだけで全体を強く推測できることを表す。",
     "At that restaurant, the very look of the food tells you it's prepared by professionals."),
    (4, "～にわたって", "", ["この","調査は","10年に","わたって"], "続けられてきた。", 4,
     "時間や範囲の広がりを表し、その全範囲で何かが行われたことを示す。",
     "This research has been carried out over a span of ten years."),
    (4, "～を通じて", "", ["読書を","通じて","様々な","知識を"], "得ることができる。", 2,
     "手段・経路として何かを利用すること、または期間の全体を通してという意味。",
     "Through reading, one can acquire various kinds of knowledge."),
    (4, "～限り", "", ["力の","限り","最後まで","諦めずに"], "戦いたい。", 2,
     "範囲や期間の上限を示し、その範囲の全てという意味を表す。",
     "I want to fight to the very end with all my strength, without giving up."),
    (4, "～だけ", "", ["好きな","だけ","食べて","いいですよ"], "と言われた。", 2,
     "制限なしにその範囲のすべてを行ってよいことを示す。好きなように、という許可。",
     "I was told, \"You can eat as much as you like.\""),

    # ========== Lesson 5 ==========
    (5, "～に限り", "", ["本日に","限り","全商品が","半額で"], "ご購入いただけます。", 2,
     "ある条件の場合のみ特別に許可されることを表す。案内文や告知でよく使われる。",
     "For today only, all items may be purchased at half price."),
    (5, "～限りでは", "", ["私が","知っている","限りでは","彼は"], "まだ帰国していない。", 3,
     "自分の知識や情報の範囲を限定して判断を述べる表現。断定を避ける効果がある。",
     "As far as I know, he has not yet returned to his home country."),
    (5, "～に限って", "", ["急いで","いる時に","限って","電車が"], "遅れるものだ。", 3,
     "よりにもよって最悪のタイミングで悪いことが起こるという不運を強調する表現。",
     "It's precisely when you're in a hurry that the trains tend to be delayed."),

    # ========== Lesson 11 ==========
    (11, "～を問わず", "", ["このアプリは","年齢を","問わず","誰でも"], "楽しむことができる。", 3,
     "条件や属性に関係なく、すべてに当てはまることを示す。制限なしの表現。",
     "This app can be enjoyed by anyone, regardless of age."),
    (11, "～にかかわらず", "", ["天候に","かかわらず","試合は","予定通り"], "行われます。", 2,
     "外部の条件に影響を受けないことを強調する。どんな状況でも変わらない。",
     "Regardless of the weather, the match will be held as scheduled."),
    (11, "～もかまわず", "", ["彼は","人目も","かまわず","大声で"], "泣き出した。", 3,
     "普通は気を遣うべき場面で、それを全く気にしない様子を表す。",
     "He broke into loud sobs, not caring who might see him."),
    (11, "～はともかく", "", ["味は","ともかく","値段は","とても"], "手ごろだ。", 2,
     "一つの話題を一旦脇に置いて、別の側面に焦点を当てる表現。",
     "Setting taste aside, the price is very reasonable."),
    (11, "～はさておき", "", ["冗談は","さておき","本題に","入りましょう"], "か。", 2,
     "今の話題を後回しにして、別の（より重要な）話題に切り替える表現。",
     "Jokes aside, shall we get down to the main topic?"),

    # ========== Lesson 12 ==========
    (12, "～わけがない", "", ["彼が","そんな","嘘を","つくわけがない"], "。", 4,
     "ある事態の可能性を強く否定する。「そんなことは絶対にありえない」という確信。",
     "There's no way he would tell such a lie."),
    (12, "～どころか", "", ["宿題を","終える","どころか","まだ"], "始めてもいない。", 3,
     "期待や予想よりもはるかに低い（または高い）現実を示す。強い否定や対比の表現。",
     "Far from finishing my homework, I haven't even started it."),
    (12, "～もんか", "", ["あんな","失礼な店に","二度と","行くもんか"], "。", 4,
     "話し言葉で「絶対に～しない」という強い拒否を表す。感情的な否定。",
     "There's no way I'm ever going back to that rude restaurant."),
    (12, "～というわけではない", "", ["嫌いだ","という","わけではない","が"], "あまり食べたくない。", 3,
     "部分否定で「完全にそうとは限らない」と和らげて言う表現。ニュアンスを調整する。",
     "It's not that I dislike it, but I don't really feel like eating it."),
    (12, "～というものではない", "", ["値段が","高ければ","いいという","ものではない"], "。", 4,
     "一般的な考えや常識を否定する。「必ずしもそうとは言えない」という反論。",
     "It's not as though something is good simply because it's expensive."),

    # ========== Lesson 13 ==========
    (13, "～とは", "", ["締め切りが","明日","だとは","全く"], "知らなかった。", 3,
     "驚きや意外性を表す。「～なんて信じられない」という気持ちを込める。",
     "I had no idea at all that the deadline was tomorrow."),
    (13, "～といえば", "", ["京都","といえば","やはり","寺や"], "神社が有名だ。", 2,
     "話題を導入し、そこから連想される代表的な情報を続ける表現。",
     "Speaking of Kyoto, it's of course famous for its temples and shrines."),
    (13, "～といったら", "", ["富士山の","美しさ","といったら","言葉に"], "できないほどだ。", 3,
     "強い感情や驚きを伴う評価を表す。程度が非常に大きいことを強調。",
     "The beauty of Mt. Fuji is almost beyond words."),
    (13, "～のこととなると", "", ["普段は","冷静な","父も","野球のこととなると"], "興奮する。", 4,
     "特定の話題になると、普段とは違う特別な反応を見せることを表す。",
     "My normally calm father gets excited whenever the topic turns to baseball."),

    # ========== Lesson 14 ==========
    (14, "～にもかかわらず", "", ["雨が","降っているに","もかかわらず","試合は"], "続行された。", 3,
     "逆接を強調する硬い表現。普通なら影響を受けるはずの状況でも結果が変わらない。",
     "Despite the fact that it was raining, the match continued."),
    (14, "～ものの", "", ["日本語を","10年勉強した","ものの","まだ"], "新聞は読みにくい。", 3,
     "「～したけれど」の意味で、予想と違う結果を導く逆接表現。やや書き言葉的。",
     "Although I've studied Japanese for ten years, newspapers are still difficult for me."),
    (14, "～ながら", "", ["狭い","ながら","我が家は","とても"], "落ち着く。", 2,
     "逆接で「～だけれども」の意味。形容詞や名詞に接続し、状態の対比を表す。",
     "Small though it may be, my home is very relaxing."),
    (14, "～つつ", "", ["体に","悪いと","知りつつ","夜食を"], "やめられない。", 3,
     "「～しているのに」の逆接を表す書き言葉的な表現。意識と行動の矛盾に使うことが多い。",
     "Even though I know it's bad for me, I can't stop my late-night snacking."),
    (14, "～からといって", "", ["安い","からといって","品質が","悪い"], "とは限らない。", 2,
     "ある理由だけで当然のように結論を出すことを否定する文脈で使う。",
     "Just because something is cheap doesn't necessarily mean its quality is poor."),

    # ========== Lesson 15 ==========
    (15, "～とすれば", "", ["今から","出発する","とすれば","何時に"], "着くだろうか。", 3,
     "仮定を立てて、その上での推量や結論を述べる表現。「仮に～したら」の意味。",
     "If we leave now, what time do you think we'll arrive?"),
    (15, "～ものなら", "", ["できる","ものなら","もう一度","学生時代に"], "戻りたい。", 2,
     "実現が非常に難しい願望を表す仮定表現。「もしも可能なら」という切ない気持ち。",
     "If I could, I would love to return to my student days once more."),
    (15, "～ようものなら", "", ["約束を","破ろう","ものなら","二度と"], "信用されないだろう。", 3,
     "「もし～したら大変なことになる」と悪い結果を警告する強い仮定表現。",
     "If you were to break the promise, you would never be trusted again."),
    (15, "～ないことには", "", ["実物を","見ない","ことには","判断"], "しようがない。", 3,
     "「～しなければ…できない」という必要条件を表す。それなしでは不可能という意味。",
     "Without actually seeing the real thing, there's no way to make a judgment."),
    (15, "～抜きにしては", "", ["彼の","協力を","抜きにしては","この"], "プロジェクトは成功しなかっただろう。", 3,
     "不可欠な要素を強調する。「～なしでは成り立たない」という意味。",
     "Without his cooperation, this project would not have succeeded."),
    (15, "～にせよ", "", ["どんな","理由が","あったに","せよ"], "遅刻はよくない。", 4,
     "「～であっても」の意味で、どんな場合でも結論が変わらないことを示す譲歩表現。",
     "Whatever the reason may have been, being late is not acceptable."),

    # ========== Lesson 6 ==========
    (6, "～に限らず", "", ["この図書館は","学生に","限らず","地域の"], "住民も利用できる。", 3,
     "ある対象だけでなく、他の範囲にも同様に当てはまることを表す。",
     "This library can be used not only by students but also by local residents."),
    (6, "～のみならず", "", ["彼は","国内の","みならず","海外でも"], "高く評価されている。", 3,
     "「だけでなく」の硬い表現で、範囲がさらに広がることを強調する書き言葉。",
     "He is highly regarded not only domestically but also internationally."),
    (6, "～ばかりか", "", ["彼女は","英語","ばかりか","中国語も"], "流暢に話せる。", 3,
     "一つだけでなくさらに別のことも加わることを驚きを込めて表す表現。",
     "She can speak not only English but also Chinese fluently."),
    (6, "～はもとより", "", ["社長は","もとより","社員","全員が"], "この問題に取り組んでいる。", 2,
     "当然のことに加えて、さらに別のことも含まれることを示す。改まった表現。",
     "Not only the president, but all employees are working on this issue."),
    (6, "～上に", "", ["この店は","味がいい","上に","値段も"], "手ごろだ。", 3,
     "一つの好ましい（または悪い）点に加え、さらに別の点もあることを強調する。",
     "This restaurant has good food, and on top of that, the prices are reasonable."),

    # ========== Lesson 7 ==========
    (7, "～に関して", "", ["その","事件に","関して","警察が"], "調査を進めている。", 3,
     "話題の対象を明確に示す硬い表現。「～について」のフォーマル版。",
     "The police are conducting an investigation regarding that incident."),
    (7, "～をめぐって", "", ["新しい","法案を","めぐって","激しい"], "議論が行われている。", 3,
     "ある問題や話題を中心に様々な意見や動きがあることを示す。",
     "Intense debate is taking place surrounding the new bill."),
    (7, "～にかけては", "", ["料理の","速さに","かけては","彼女に"], "かなう人はいない。", 2,
     "特定の能力や分野で他より優れていることを表す。自信や評価の表現。",
     "When it comes to cooking speed, no one can match her."),
    (7, "～に対して", "", ["若者に","対して","もっと","働く場を"], "提供すべきだ。", 2,
     "動作や態度が向かう相手を示す。対象を明確にする表現。",
     "We should provide more workplaces for young people."),
    (7, "～にこたえて", "", ["市民の","要望に","こたえて","公園が"], "新しく整備された。", 3,
     "外部からの期待や求めに応じて何かを行うことを表す。",
     "In response to citizens' requests, a park was newly developed."),

    # ========== Lesson 8 ==========
    (8, "～をもとに", "", ["実際の","事件を","もとに","この"], "映画は作られた。", 3,
     "素材や材料としてあるものを参考にして何かを作ることを表す。",
     "This movie was made based on an actual incident."),
    (8, "～に基づいて", "", ["科学的な","データに","基づいて","政策を"], "決定すべきだ。", 3,
     "根拠や原則に従って何かを行うことを示す。信頼性を強調する表現。",
     "Policies should be decided based on scientific data."),
    (8, "～に沿って", "", ["川に","沿って","桜の","木が"], "植えられている。", 2,
     "ある方針や道筋に従って進むことを示す。物理的にも抽象的にも使える。",
     "Cherry trees are planted along the river."),
    (8, "～のもとで", "", ["優れた","指導者の","もとで","若い"], "選手が成長している。", 3,
     "影響や保護を受ける環境・条件を示す。権威や状況の下で行動することを表す。",
     "Young athletes are developing under an excellent coach."),
    (8, "～向けに", "", ["この教材は","初心者","向けに","作られた"], "ものです。", 3,
     "対象となる層や目的に合わせて何かを設計・提供することを示す。",
     "This textbook was made for beginners."),

    # ========== Lesson 9 ==========
    (9, "～につれて", "", ["年を","取るに","つれて","体力が"], "衰えてくる。", 3,
     "一方が変化すると、それに比例してもう一方も変化することを表す。",
     "As you get older, your physical strength declines."),
    (9, "～にしたがって", "", ["高度が","上がるに","したがって","気温が"], "下がっていく。", 3,
     "ある基準の変化に連動して別の変化が起きることを表す。規則や指示に従う意味もある。",
     "As the altitude increases, the temperature drops."),
    (9, "～に伴って", "", ["人口の","増加に","伴って","住宅の"], "需要も高まっている。", 3,
     "ある変化や出来事と連動して別の事態も生じることを表す。フォーマルな表現。",
     "Along with the population increase, the demand for housing is also rising."),
    (9, "～に応じて", "", ["経験に","応じて","給料が","上がる"], "仕組みになっている。", 2,
     "条件や状況の程度に合わせて対応が変わることを示す。柔軟な対応の表現。",
     "The system is set up so that salary increases according to experience."),
    (9, "～につけ", "", ["この曲を","聞く","につけ","学生時代を"], "思い出す。", 3,
     "ある動作や状況がきっかけとなり、いつもある感情や行動が生じることを表す。",
     "Whenever I hear this song, I recall my student days."),

    # ========== Lesson 10 ==========
    (10, "～やら", "", ["引っ越しで","掃除やら","荷造りやら","とても"], "忙しい。", 3,
     "複数の事柄を曖昧に列挙し、煩雑さや大変さを表す口語的表現。",
     "I'm very busy with cleaning, packing, and so on for the move."),
    (10, "～というか", "", ["彼は","真面目","というか","融通が"], "きかないタイプだ。", 3,
     "言い方を迷いながら、より適切な表現を探して言い換える話し言葉の表現。",
     "He's serious, or rather, the inflexible type."),
    (10, "～にしても", "", ["留学する","にしても","費用の","問題を"], "解決しなければならない。", 2,
     "仮にその選択をする場合でも、別の条件が必要であることを表す。",
     "Even if you study abroad, you have to solve the cost issue."),
    (10, "～といった", "", ["東京や","大阪","といった","大都市は"], "人口が多い。", 3,
     "具体的な例を挙げて、同種のものが他にもあることを示す例示の表現。",
     "Large cities such as Tokyo and Osaka have large populations."),

    # ========== Lesson 16 ==========
    (16, "～によって", "", ["この建物は","有名な","建築家に","よって"], "設計された。", 4,
     "動作の主体や手段・原因を示す。受身文の動作主としてもよく使われる。",
     "This building was designed by a famous architect."),
    (16, "～ものだから", "", ["電車が","遅れた","ものだから","会議に"], "間に合わなかった。", 3,
     "言い訳や弁解のニュアンスで理由を述べる口語的表現。予想外だった含みがある。",
     "Because the train was delayed, I couldn't make it to the meeting on time."),
    (16, "～おかげで/せいで", "", ["先生の","おかげで","試験に","合格"], "することができた。", 2,
     "良い結果が得られた原因を感謝を込めて示す。逆に悪い結果の場合は責任を示す。",
     "Thanks to my teacher, I was able to pass the exam."),
    (16, "～のあまり", "", ["嬉しさの","あまり","涙が","出て"], "きてしまった。", 2,
     "感情が過度に強くなった結果、思わず何かが起きてしまうことを表す。",
     "I was so happy that tears came to my eyes."),
    (16, "～につき", "", ["工事","につき","この道は","通行"], "できません。", 2,
     "理由や原因を簡潔に示す硬い表現。掲示やお知らせでよく使われる。",
     "Due to construction work, this road is closed to traffic."),

    # ========== Lesson 17 ==========
    (17, "～ことだし", "", ["天気も","いい","ことだし","散歩に"], "出かけよう。", 3,
     "ある事情を軽い理由として挙げ、次の行動を提案する口語的表現。",
     "Since the weather is nice, let's go out for a walk."),
    (17, "～のことだから", "", ["真面目な","彼の","ことだから","きっと"], "時間通りに来るだろう。", 3,
     "相手の性格や特徴をよく知っている前提で、当然の推量をする表現。",
     "Knowing him and how serious he is, he'll surely come on time."),
    (17, "～だけに", "", ["さすが","プロな","だけに","仕事が"], "丁寧だ。", 3,
     "前の事柄から当然そうなるという強い納得や期待通りの結果を表す。",
     "As expected of a professional, the work is meticulous."),
    (17, "～ばかりに", "", ["一言","余計なことを","言った","ばかりに"], "友人を傷つけてしまった。", 4,
     "たった一つの原因で悪い結果を招いたことを後悔する表現。",
     "Just because I said one unnecessary thing, I ended up hurting my friend."),
    (17, "～からには/以上", "", ["約束した","からには","最後まで","責任を"], "持つべきだ。", 2,
     "ある事実を前提として、そこから当然生じる義務や決意を表す。",
     "Since you made a promise, you should take responsibility to the end."),

    # ========== Lesson 18 ==========
    (18, "～がたい", "", ["あの","事故の","光景は","忘れがたい"], "ものだった。", 4,
     "心理的に受け入れにくい、またはそうすることが困難であることを表す書き言葉的表現。",
     "The sight of that accident was something hard to forget."),
    (18, "～かねる", "", ["その","ご要望には","お応え","しかねます"], "。", 4,
     "丁寧に断る場面で「～できません」を柔らかく伝える表現。ビジネスでよく使われる。",
     "We are unable to accommodate that request."),
    (18, "～わけにはいかない", "", ["体調が","悪くても","休む","わけにはいかない"], "。", 4,
     "社会的・道徳的な制約があるため、そうしたくてもできないことを表す。",
     "Even if I feel unwell, I cannot afford to take a day off."),
    (18, "～ようがない", "", ["連絡先が","わからなければ","連絡の","しようがない"], "。", 4,
     "方法や手段が存在しないため不可能であることを表す。",
     "If you don't know the contact information, there's no way to get in touch."),
    (18, "～どころではない", "", ["仕事が","忙しくて","旅行","どころではない"], "。", 4,
     "ある事情のせいで本来したいことが全くできない状況を強く表す。",
     "I'm so busy with work that a trip is out of the question."),
    (18, "～得る", "", ["そんな","ミスは","誰にでも","起こり得る"], "ことだ。", 4,
     "あることが実現する可能性があることを表す書き言葉的表現。",
     "Such a mistake is something that can happen to anyone."),

    # ========== Lesson 19 ==========
    (19, "～わりに", "", ["この料理は","手間が","かかった","わりに"], "あまりおいしくなかった。", 4,
     "前の事柄から予想される程度と実際の結果にギャップがあることを表す。",
     "For the effort I put in, this dish didn't taste very good."),
    (19, "～にしては", "", ["初めて","作った","にしては","なかなか"], "上手にできた。", 3,
     "その条件から期待される水準と違う結果であることを驚きを込めて表す。",
     "For something you made for the first time, it turned out quite well."),
    (19, "～だけあって", "", ["有名な","シェフ","だけあって","味は"], "抜群だった。", 3,
     "前の事柄にふさわしい結果であることを納得や評価を込めて表す。",
     "As you'd expect from a famous chef, the taste was outstanding."),
    (19, "～として", "", ["彼は","医師","として","地域に"], "貢献している。", 3,
     "役割や立場・資格を示し、その立場で何かをすることを表す。",
     "He is contributing to the community as a doctor."),
    (19, "～にとって", "", ["子供に","とって","遊びは","大切な"], "学びの場だ。", 2,
     "判断や評価の主体となる視点を示す。「～の立場から見ると」の意味。",
     "For children, play is an important place of learning."),
    (19, "～にしたら", "", ["親に","したら","子供の","安全が"], "一番心配だろう。", 2,
     "ある人の立場に立って考えた場合の気持ちや判断を推量する表現。",
     "From a parent's standpoint, their child's safety is probably the biggest concern."),

    # ========== Lesson 20 ==========
    (20, "～ところ", "", ["先生に","相談した","ところ","良い"], "アドバイスをもらえた。", 3,
     "ある行動をした結果、何がわかったか・何が起きたかを述べる表現。",
     "When I consulted my teacher, I received good advice."),
    (20, "～きり", "", ["彼は","5年前に","出かけた","きり"], "帰ってこない。", 4,
     "ある動作を最後に、その状態がずっと続いていることを表す。",
     "He left five years ago and has not come back since."),
    (20, "～あげく", "", ["長時間","悩んだ","あげく","結局"], "何も決められなかった。", 3,
     "長い過程の後に望ましくない結果になったことを表す。マイナスの結末に使う。",
     "After agonizing for a long time, I ultimately couldn't decide anything."),
    (20, "～末に", "", ["何度も","話し合った","末に","ようやく"], "合意に達した。", 3,
     "長い努力や苦労の後にようやく結果が出たことを表す。",
     "After discussing it many times, we finally reached an agreement."),
    (20, "～ところだった", "", ["もう少しで","電車に","乗り遅れる","ところだった"], "。", 4,
     "悪い結果になりかけたが、ぎりぎりで回避できたことを表す。危機一髪の表現。",
     "I almost missed the train."),
    (20, "～ずじまい", "", ["買った","本を","読まず","じまいで"], "本棚に置いてある。", 4,
     "するつもりだったことが結局できないまま終わってしまったことを表す。残念な気持ち。",
     "The book I bought is sitting on the shelf, unread."),

    # ========== Lesson 21 ==========
    (21, "～なんて/くらい", "", ["漢字を","覚える","くらい","簡単な"], "ことだ。", 3,
     "対象を軽く見たり、程度が低いことを強調したりする表現。",
     "Something like memorizing kanji is an easy matter."),
    (21, "～なんか", "", ["あんな","映画","なんか","二度と"], "見たくない。", 3,
     "対象を低く評価し、軽蔑や否定的な気持ちを込める口語表現。",
     "I never want to watch a movie like that again."),
    (21, "～まで", "", ["信頼していた","友人","まで","私を"], "裏切るとは思わなかった。", 3,
     "意外なものや極端な例を挙げて、事態の深刻さを強調する表現。",
     "I never thought that even a friend I trusted would betray me."),
    (21, "～さえ", "", ["名前","さえ","書けば","応募"], "できます。", 2,
     "最小限の条件を提示し、「それだけで十分」または「それすらも」という意味を表す。",
     "You can apply just by writing your name."),
    (21, "～でも", "", ["コーヒー","でも","飲みながら","話しましょう"], "。", 2,
     "軽い提案や例示を表し、「～のようなもの」という気軽さを示す。",
     "Let's talk while having some coffee or something."),

    # ========== Lesson 22 ==========
    (22, "～とみえる", "", ["彼は","疲れている","とみえて","早めに"], "帰っていった。", 3,
     "外見や状況から判断して推測する表現。客観的な観察に基づく。",
     "He appeared to be tired, so he went home early."),
    (22, "～かねない", "", ["このまま","放置すれば","大事故に","なりかねない"], "。", 4,
     "悪い結果になる可能性が十分あることを警告する表現。否定的な推量。",
     "If left as it is, it could easily turn into a serious accident."),
    (22, "～おそれがある", "", ["台風が","接近し","大雨の","おそれがある"], "。", 4,
     "望ましくない事態が起こる可能性があることをフォーマルに警告する表現。",
     "A typhoon is approaching, and there is a risk of heavy rain."),
    (22, "～まい", "", ["あんな","失敗は","二度と","すまい"], "と心に誓った。", 4,
     "話し手の強い否定の意志や、そうならないだろうという推量を表す書き言葉。",
     "I vowed to myself that I would never make such a mistake again."),
    (22, "～に違いない", "", ["この足跡は","犯人の","ものに","違いない"], "。", 4,
     "確信を持って断定する表現。証拠や状況から強く推測している。",
     "These footprints must belong to the culprit."),
    (22, "～にきまっている", "", ["あの店は","いつも","混んでいるに","きまっている"], "。", 4,
     "経験や常識に基づいて当然そうだと断言する口語的表現。",
     "That restaurant is obviously always crowded."),

    # ========== Lesson 23 ==========
    (23, "～にすぎない", "", ["私の","意見は","一つの","参考にすぎない"], "。", 4,
     "物事の程度や重要性を低く見積もり、「たったそれだけ」と控えめに述べる表現。",
     "My opinion is nothing more than one reference."),
    (23, "～にほかならない", "", ["この成功は","チーム","全員の","努力にほかならない"], "。", 4,
     "それ以外に理由や正体はないと強く断定する表現。「まさにそれだ」という確信。",
     "This success is nothing other than the effort of the whole team."),
    (23, "～に越したことはない", "", ["健康の","ためには","運動するに","越したことはない"], "。", 4,
     "それが最善の選択であることを表す。「できればそうすべき」という助言。",
     "For your health, nothing is better than exercising."),
    (23, "～よりほかない", "", ["電車が","止まった","以上","歩くより"], "ほかない。", 4,
     "他に選択肢がなく、それしかできないことを表す。やむを得ない状況。",
     "Since the trains have stopped, there's no choice but to walk."),
    (23, "～べきだ", "", ["学生は","もっと","本を","読むべきだ"], "。", 4,
     "道徳的・社会的に当然そうすべきだという義務や助言を表す。",
     "Students should read more books."),
    (23, "～ものだ", "", ["時間が","経つのは","本当に","早いものだ"], "。", 4,
     "一般的な真理や感慨を述べる表現。「つくづくそうだ」という実感。",
     "Time really does pass quickly."),
    (23, "～ことはない", "", ["そんなに","心配する","ことはない","から"], "安心してください。", 3,
     "ある行動の必要性を否定する。「わざわざ～しなくてよい」という助言。",
     "There's no need to worry so much, so please relax."),

    # ========== Lesson 24 ==========
    (24, "～ではないか", "", ["もっと","自分を","信じてみては","いかがではないか"], "。", 4,
     "相手に柔らかく提案や勧めをする表現。「～したらどうだろう」の意味。",
     "Why don't you try believing in yourself more?"),
    (24, "～ことだ", "", ["健康で","いたければ","早く寝る","ことだ"], "。", 4,
     "当然すべきことを助言として述べる表現。「そうするのがよい」という意味。",
     "If you want to stay healthy, the thing to do is go to bed early."),

    # ========== Lesson 25 ==========
    (25, "～しょうがない/てならない", "", ["故郷が","懐かしくて","しょうがない","のは"], "自然なことだ。", 3,
     "ある感情が抑えられないほど強く湧き上がることを表す。自然に生じる気持ち。",
     "It's natural that you can't help missing your hometown."),
    (25, "～ずにはいられない", "", ["あの映画を","見たら","泣かずには","いられない"], "だろう。", 4,
     "自分の意志ではどうにもならず、つい行動してしまうことを表す。",
     "If you watch that movie, you probably won't be able to help crying."),
    (25, "～ざるを得ない", "", ["証拠が","ある","以上","認めざるを得ない"], "。", 4,
     "状況的にそうするしか選択肢がないことを表す。仕方なく受け入れる気持ち。",
     "Given the evidence, I have no choice but to admit it."),

    # ========== Lesson 26 ==========
    (26, "～ものがある", "", ["彼の","演奏には","人を","感動させるものがある"], "。", 4,
     "心に深く響く特別な性質や印象を感じ取ることを表す。",
     "There's something about his performance that moves people."),
    (26, "～ことか", "", ["合格の","知らせを","聞いて","どんなに嬉しかったことか"], "。", 4,
     "強い感情を感嘆として表現する。程度が計り知れないことを示す。",
     "How happy I was when I heard the news that I passed!"),
]

out = []
for i, (lesson, grammar, prefix, answer, suffix, star, explanation, translation) in enumerate(Q, 1):
    assert len(answer) == 4, f"Q{i} {grammar} has {len(answer)} tokens"
    assert 1 <= star <= 4
    out.append({
        "id": i,
        "lesson": lesson,
        "prefix": prefix,
        "suffix": suffix,
        "answer": answer,
        "star": star,
        "grammar": grammar,
        "explanation": explanation,
        "translation": translation,
    })

target = os.path.join(os.path.dirname(__file__), "ordering-questions.json")
with open(target, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print(f"Wrote {len(out)} questions to {target}")
by_lesson = {}
for q in out:
    by_lesson.setdefault(q["lesson"], 0)
    by_lesson[q["lesson"]] += 1
for l in sorted(by_lesson):
    print(f"  Lesson {l}: {by_lesson[l]} questions")
